"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$python\
$nodejs\
$bun\
$golang\
$rust\
$battery\
$git_branch\
$git_status\
$line_break\
$status\
$character"""

[directory]
truncation_length = 3
format = "[$path]($style) "
style = "bold cyan"

[git_branch]
format = "\\[[$branch]($style)\\] "
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
conflicted = "!${count}"
untracked = "?${count}"
stashed = ""
modified = "±${count}"
staged = "+${count}"
renamed = ""
deleted = "✘${count}"
style = "bold yellow"

[python]
format = "λ [$pyenv_prefix$version]($style)[$virtualenv]($style) "
version_format = "${major}.${minor}"
style = "green"

[nodejs]
format = "⬢ [$version]($style) "
version_format = "${major}.${minor}"
style = "green"

[golang]
format = "◉ [$version]($style) "
version_format = "${major}.${minor}"
style = "green"

[rust]
format = "⚙ [$version]($style) "
version_format = "${major}.${minor}"
style = "green"

[bun]
format = "● [$version]($style) "
version_format = "${major}.${minor}"
style = "green"

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = "⚡"
unknown_symbol = ""
empty_symbol = "!"

[[battery.display]]
threshold = 20
style = "bold red"
discharging_symbol = "⚡"

[status]
format = '[✗$status]($style) '
style = "bold red"
disabled = false

[character]
success_symbol = '[.](bold green)'
error_symbol = '[.](bold red)'
